"""Agregar estado a publicaciones

Revision ID: 07df0ab57939
Revises: 73feef89d929
Create Date: 2025-11-15 16:13:52.347007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07df0ab57939'
down_revision = '73feef89d929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
