"""Agregar boludez en solicitud de contacto

Revision ID: 12e9a185667c
Revises: ff94da9ef62d
Create Date: 2025-11-24 17:24:11.516470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e9a185667c'
down_revision = 'ff94da9ef62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_contacto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_contacto', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_contacto', schema=None) as batch_op:
        batch_op.drop_column('tipo_contacto')

    # ### end Alembic commands ###
