"""Agregar soporte para reportar usuarios y comentarios

Revision ID: 133e44fd8daa
Revises: e459fc3998f6
Create Date: 2025-11-23 11:00:02.208538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133e44fd8daa'
down_revision = 'e459fc3998f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_comentario', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_usuario_reportado', sa.Integer(), nullable=True))
        batch_op.alter_column('id_publicacion',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario_reportado'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'comentarios', ['id_comentario'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_publicacion',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id_usuario_reportado')
        batch_op.drop_column('id_comentario')

    # ### end Alembic commands ###
