"""saque tabla personas

Revision ID: 147d20cdfafc
Revises: 86a8b7cbd5c8
Create Date: 2025-06-03 14:59:35.955954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147d20cdfafc'
down_revision = '86a8b7cbd5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persona')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('persona_pkey'))
    )
    # ### end Alembic commands ###
