"""Agregar logs

Revision ID: 1a74006a30f1
Revises: f82813845cc2
Create Date: 2025-09-24 16:15:14.167794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a74006a30f1'
down_revision = 'f82813845cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('timestamp_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_start_processing', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_send_supabase', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_return_supabase', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_send_cloudinary', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_return_cloudinary', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_send_firebase', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_return_firebase', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_response_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=True),
    sa.Column('payload_size', sa.Integer(), nullable=True),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_logs')
    # ### end Alembic commands ###
