"""Agregar etiquetas y relación many-to-many

Revision ID: 23c27706f862
Revises: fc44f01ccadb
Create Date: 2025-07-23 13:19:08.881795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c27706f862'
down_revision = 'fc44f01ccadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiquetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('publicacion_etiqueta',
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('id_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_etiqueta'], ['etiquetas.id'], ),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ),
    sa.PrimaryKeyConstraint('id_publicacion', 'id_etiqueta')
    )
    op.execute('ALTER TABLE localidades ALTER COLUMN id_departamento TYPE INTEGER USING id_departamento::integer')
    op.create_foreign_key(None, 'localidades', 'departamentos', ['id_departamento'], ['id'])

    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.alter_column('id_locacion',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.drop_column('etiquetas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etiquetas', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('id_locacion',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('localidades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_departamento',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.drop_table('publicacion_etiqueta')
    op.drop_table('etiquetas')
    # ### end Alembic commands ###
