"""Agregar id_localidad a usuario

Revision ID: 4679dd6a7e9e
Revises: 133e44fd8daa
Create Date: 2025-11-23 13:31:33.335650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4679dd6a7e9e'
down_revision = '133e44fd8daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_localidad', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'localidades', ['id_localidad'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_localidad')

    # ### end Alembic commands ###
