"""notificaciones

Revision ID: 58af331f6d3a
Revises: 0812eb8f2cf0
Create Date: 2025-08-12 17:38:27.796808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58af331f6d3a'
down_revision = '0812eb8f2cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_publicacion', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'publicaciones', ['id_publicacion'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_publicacion')

    # ### end Alembic commands ###
