"""recuperacion

Revision ID: 73feef89d929
Revises: ed2fd56f94c5
Create Date: 2025-10-25 13:44:58.466016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73feef89d929'
down_revision = 'ed2fd56f94c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiquetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('timestamp_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_start_processing', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_send_supabase', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_return_supabase', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_send_cloudinary', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_return_cloudinary', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_send_firebase', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_return_firebase', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_response_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=True),
    sa.Column('payload_size', sa.Integer(), nullable=True),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_provincia', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.ForeignKeyConstraint(['id_provincia'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=28), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('foto_perfil_url', sa.Text(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telefono_pais', sa.Text(), nullable=True),
    sa.Column('telefono_numero_local', sa.BigInteger(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('localidades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('id_departamento', sa.Integer(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_locacion', sa.BigInteger(), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coordenadas', sa.ARRAY(sa.Float()), nullable=True),
    sa.ForeignKeyConstraint(['id_locacion'], ['localidades.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_anterior', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_publicacion', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_publicacion', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publicacion_etiqueta',
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('id_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_etiqueta'], ['etiquetas.id'], ),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ),
    sa.PrimaryKeyConstraint('id_publicacion', 'id_etiqueta')
    )
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportes')
    op.drop_table('publicacion_etiqueta')
    op.drop_table('notificaciones')
    op.drop_table('imagenes')
    op.drop_table('comentarios')
    op.drop_table('publicaciones')
    op.drop_table('localidades')
    op.drop_table('usuarios')
    op.drop_table('departamentos')
    op.drop_table('roles')
    op.drop_table('request_logs')
    op.drop_table('provincias')
    op.drop_table('etiquetas')
    # ### end Alembic commands ###
