"""inicio

Revision ID: 86a8b7cbd5c8
Revises: 
Create Date: 2025-06-03 14:55:03.632184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86a8b7cbd5c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=28), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('foto_perfil_url', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('num_publicaciones', sa.Integer(), nullable=True),
    sa.Column('num_publicaciones_dia', sa.Integer(), nullable=True),
    sa.Column('telefono_pais', sa.Text(), nullable=True),
    sa.Column('telefono_numero', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_table('ubicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('codigo_postal', sa.Integer(), nullable=True),
    sa.Column('provincia', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.Text(), nullable=True),
    sa.Column('calle', sa.Text(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_ubicacion', sa.Integer(), nullable=True),
    sa.Column('grupo', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('id_anterior', sa.Integer(), nullable=True),
    sa.Column('id_siguiente', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('foto_url_1', sa.Text(), nullable=True),
    sa.Column('foto_url_2', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_anterior'], ['publicaciones.id'], ),
    sa.ForeignKeyConstraint(['id_siguiente'], ['publicaciones.id'], ),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['ubicaciones.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('usuarioid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('foto_de_perfil', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('firebase_uid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('usuarioid', name=op.f('usuario_pkey')),
    sa.UniqueConstraint('email', name=op.f('usuario_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('firebase_uid', name=op.f('usuario_firebase_uid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('publicaciones')
    op.drop_table('ubicaciones')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
