"""Agregar cascada en notificaciones al borrar usuario

Revision ID: 8fe007cb8e2e
Revises: a4ef56a0e0dd
Create Date: 2025-11-17 10:00:18.343831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe007cb8e2e'
down_revision = 'a4ef56a0e0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notificaciones_id_usuario_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notificaciones_id_usuario_fkey'), 'usuarios', ['id_usuario'], ['id'])

    # ### end Alembic commands ###
