"""Agregar cascada para imágenes y otras relaciones de usuario

Revision ID: 98430544fd4b
Revises: 8fe007cb8e2e
Create Date: 2025-11-17 10:11:23.737834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98430544fd4b'
down_revision = '8fe007cb8e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagenes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('imagenes_id_publicacion_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'publicaciones', ['id_publicacion'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notificaciones_id_publicacion_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'publicaciones', ['id_publicacion'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notificaciones_id_publicacion_fkey'), 'publicaciones', ['id_publicacion'], ['id'])

    with op.batch_alter_table('imagenes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('imagenes_id_publicacion_fkey'), 'publicaciones', ['id_publicacion'], ['id'])

    # ### end Alembic commands ###
