"""Agregar cascada al borrar usuario

Revision ID: a4ef56a0e0dd
Revises: ad8cfcbd1e13
Create Date: 2025-11-17 09:56:32.175592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ef56a0e0dd'
down_revision = 'ad8cfcbd1e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comentarios_id_publicacion_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comentarios_id_usuario_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'publicaciones', ['id_publicacion'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('publicaciones_id_usuario_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('publicaciones_id_usuario_fkey'), 'usuarios', ['id_usuario'], ['id'])

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comentarios_id_usuario_fkey'), 'usuarios', ['id_usuario'], ['id'])
        batch_op.create_foreign_key(batch_op.f('comentarios_id_publicacion_fkey'), 'publicaciones', ['id_publicacion'], ['id'])

    # ### end Alembic commands ###
