"""Agregar columna estado a Usuario

Revision ID: ad8cfcbd1e13
Revises: 07df0ab57939
Create Date: 2025-11-16 20:44:18.779608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8cfcbd1e13'
down_revision = '07df0ab57939'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=10), nullable=False, server_default='activo'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
