"""Solicitud de mensajes

Revision ID: dffc21f590c2
Revises: e782e394ca2c
Create Date: 2025-11-24 16:40:23.802834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffc21f590c2'
down_revision = 'e782e394ca2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_contacto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_solicitante', sa.Integer(), nullable=False),
    sa.Column('id_receptor', sa.Integer(), nullable=False),
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_receptor'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_solicitante'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_contacto')
    # ### end Alembic commands ###
