"""Agregar cascada a tablas relacionadas con usuarios y publicaciones

Revision ID: e459fc3998f6
Revises: 98430544fd4b
Create Date: 2025-11-17 10:15:59.243556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e459fc3998f6'
down_revision = '98430544fd4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion_etiqueta', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('publicacion_etiqueta_id_publicacion_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('publicacion_etiqueta_id_etiqueta_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'publicaciones', ['id_publicacion'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'etiquetas', ['id_etiqueta'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion_etiqueta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('publicacion_etiqueta_id_etiqueta_fkey'), 'etiquetas', ['id_etiqueta'], ['id'])
        batch_op.create_foreign_key(batch_op.f('publicacion_etiqueta_id_publicacion_fkey'), 'publicaciones', ['id_publicacion'], ['id'])

    # ### end Alembic commands ###
