"""Agregar tabla Categoria y fk en Publicacion

Revision ID: e782e394ca2c
Revises: 4679dd6a7e9e
Create Date: 2025-11-23 13:41:02.038194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e782e394ca2c'
down_revision = '4679dd6a7e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_categoria', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categorias', ['id_categoria'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_categoria')

    op.drop_table('categorias')
    # ### end Alembic commands ###
