"""Agregar response time a request log

Revision ID: ed2fd56f94c5
Revises: 35b2f50d04f5
Create Date: 2025-09-24 18:05:56.744048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2fd56f94c5'
down_revision = '35b2f50d04f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_time_ms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_column('response_time_ms')

    # ### end Alembic commands ###
