"""reportes

Revision ID: f3e332cbab1a
Revises: 58af331f6d3a
Create Date: 2025-09-02 17:43:06.774137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e332cbab1a'
down_revision = '58af331f6d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reportes_id_usuario_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('reportes_id_publicacion_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'publicaciones', ['id_publicacion'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reportes_id_publicacion_fkey'), 'publicaciones', ['id_publicacion'], ['id'])
        batch_op.create_foreign_key(batch_op.f('reportes_id_usuario_fkey'), 'usuarios', ['id_usuario'], ['id'])

    # ### end Alembic commands ###
