"""Agregar columna rol a usuarios

Revision ID: f82813845cc2
Revises: e36cbef62332
Create Date: 2025-09-24 15:41:29.959988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82813845cc2'
down_revision = 'e36cbef62332'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Eliminar la foreign key y la columna role_id de usuarios
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('usuarios_role_id_fkey', type_='foreignkey')
        batch_op.drop_column('role_id')
        batch_op.add_column(sa.Column('rol', sa.Text(), nullable=True))

    # 2. Ahora sí, eliminar la tabla roles
    op.drop_table('roles')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('usuarios_role_id_fkey'), 'roles', ['role_id'], ['id'])
        batch_op.drop_column('rol')

    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey')),
    sa.UniqueConstraint('nombre', name=op.f('roles_nombre_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
