"""Agregar id_localidad a usuario

Revision ID: ff94da9ef62d
Revises: dffc21f590c2
Create Date: 2025-11-24 17:08:54.242958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff94da9ef62d'
down_revision = 'dffc21f590c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_referencia', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_column('id_referencia')

    # ### end Alembic commands ###
